### ISSUE TITLE
Unable to find index.html

### ISSUE THREAD

**Issue by jebdesign** [sverrirs/jekyll-paginate-v2#1]
On build, I keep getting 'Pagination: is enabled, but I couldn't find any index.html page to use as the pagination template. Skipping pagination.'

I have a jekyll project with the following (pertinent) structure:
_layouts/blog.html (with the for loop on)
_site/blog/index.html

In _config.yml I have:
pagination:
  enabled: true
  per_page: 2

I've put the for loop as per the docs on my blog.html but nothing shows up on the built blog/index.html

**Comment by sverrirs** [comment]
Hi James, for the new pagination logic your index.html page (or what ever page you want to paginate on) needs a little bit extra front-matter. At the very least you need:
``` yml
---
layout: post
pagination: 
  enabled: true
---
```

If you only want a certain category of posts to show up in index.html (assuming you have your posts categorised either through a directory structure like `/siteroot/blog/_posts/` or using `category: blog` in the front matter of the post then you can add this to your index.html to just show posts in category 'blog':
```yml
---
layout: post
pagination: 
  enabled: true
  category: 'blog'
---
```

**Comment by jebdesign** [comment]
Thanks Sverrir. That makes sense. As you say it needs to be a 'page', where within Jekyll would I put that front-matter?

**Comment by sverrirs** [comment]
For me I have two files under `_layouts`, post.html and page.html

In this case "page.html" is intended as the template page for anything on my website that lives as a single entity (e.g. the about.html or contact.html, archive.html etc). Basically nothing that is a blog post or an article. This is what I refer to as a "page". 

As a concrete example, my main "index.html" is also a "page" this means that at the top of the file i refer to the page.html layout like so:
``` yml
---
layout: page
description: "Ramblings of Sverrir Sigmundarson"
# bunch of other front matter configuration
pagination: 
  enabled: true
  category: 'blog'
---
```

This page has pagination enabled on it and it paginates only blog posts (files under my `/blog/_posts/` folder) on this index page.

Hope this helps.
