### ISSUE TITLE
Paginate ignoring future:false

### ISSUE THREAD

**Issue by aburnsni** [sverrirs/jekyll-paginate-v2#102]
I'm still fairly new to Jekyll, but I've ran into a problem with jekyll-paginate-v2.  
In my _config.yml i have

```yml
future: false

collections:
  mycollection:
    output: true
```
My pagination page is created with all posts (linked to posted page).  This includes future posts,  but because of the `future: false` the actual post page is not created.

jekyll-paginate-v2 is ignoring the `future` setting and creating links to a pages that does not exist.
I need to be able to hide future posts from the pagination pages.
