### ISSUE TITLE
Paginating collections keeps paginating posts

### ISSUE THREAD

**Issue by aovestdipaperino** [sverrirs/jekyll-paginate-v2#103]
This is what I have in the _config.yml:
```
pagination:
  enabled: true
  per_page: 20
  permalink: '/page/:num/'
  title: ' - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail: 
    before: 5 # The number of links before the current page
    after: 5  # The number of links after the current page
  
autopages:
  enabled: true
  tags: 
    enabled: false
  categories:
    layouts:
      - category.html
    enabled: true
    trail: 
      before: 2 # The number of links before the current page
      after: 2  # The number of links after the current page
  collections:
    enabled: true
    collection: forum
    layouts:
      - autopage_forumlist.html

collections:
  forum:
    output: true
  posts:
    output: false
```

In the autopage_forumlist.html I have:
```
---
layout: default
title: "Welcome to the forum"
date: 2018-01-22 06:01:00 +0100 
autopages:
  permalink: /forum
pagination:
  enabled: true
  collection: forum
  debug: true
---
<p>Forum test list page. Something.</p>

  <h1><a href="{{ post.url }}">{{ post.title }}</a></h1>
  <p class="author">
    <span class="date">{%- assign date_format = site.minima.date_format | default: "%b %-d, %Y" -%}{{ post.date | date: date_format  }}</span> - <a href="{{ post.url }}#disqus_thread" data-disqus-identifier="{{post.url | absolute_url }}">0 comments</a>
  </p>
  <div class="content">
    {{ post.content }}
  </div>
```

Then I have ~1200 html posts files in _posts and 3 html files in _forum.
A typical file has:
```
---
layout: post
title: "Title"
date: 2018-01-22 06:01:00 +0100 
permalink: /forum/1.html
collection: forum
---
<p>Forum test</p>
```
When Jekyll builds, I see this in the output:
```
     Generating...
         AutoPages: tags pages are disabled/not configured in site.config.
         AutoPages: Generating categories pages
         AutoPages: Generating collections pages
        Pagination: ----------------------------
        Pagination: Page: forum/index.html
        Pagination:  Active configuration
        Pagination:   Enabled:          true
        Pagination:   Items per page:   20
        Pagination:   Permalink:        /page/:num/
        Pagination:   Title:             - page :num
        Pagination:   Limit:            0
        Pagination:   Sort by:          date
        Pagination:   Sort reverse:     true
        Pagination:  Active Filters
        Pagination:   Collection:       posts
        Pagination:   Offset:           0
        Pagination:   Category:         [Not set]
        Pagination:   Tag:              [Not set]
        Pagination:   Locale:           [Not set]
        Pagination:  Filtering by: Category  1214 => 1214
        Pagination:  Filtering by: Tag       1214 => 1214
        Pagination:  Filtering by: Locale    1214 => 1214
        Pagination: Rolling through the date fields for all documents
        Pagination: ----------------------------
        Pagination: Page: forum/index.html
        Pagination:  Active configuration
        Pagination:   Enabled:          true
        Pagination:   Items per page:   20
        Pagination:   Permalink:        /page/:num/
        Pagination:   Title:             - page :num
        Pagination:   Limit:            0
        Pagination:   Sort by:          date
        Pagination:   Sort reverse:     true
        Pagination:  Active Filters
        Pagination:   Collection:       forum
        Pagination:   Offset:           0
        Pagination:   Category:         [Not set]
        Pagination:   Tag:              [Not set]
        Pagination:   Locale:           [Not set]
        Pagination:  Filtering by: Category    3 => 3
        Pagination:  Filtering by: Tag         3 => 3
        Pagination:  Filtering by: Locale      3 => 3
        Pagination: Rolling through the date fields for all documents
        Pagination: Complete, processed 33 pagination page(s)
                    done in 150.761 seconds.
```

There are then 61 pages generated and index.html is then overwritten.
Seems like a bug unless I am doing something wrong. Any hints?
