### ISSUE TITLE
omit some collections from autopages? Different layout/permalink for some collections? 

### ISSUE THREAD

**Issue by spr13** [sverrirs/jekyll-paginate-v2#109]
Hi,

I tried having 'autopages' not generate a page for all collections but I couldn't do it. 

Is there a way to disable autopages for some collections?
Is there a way to have a different layout/permalink for some autopaged collections?

If not I think that feature should be added.

I personally sometimes use the collection property to store lists of data ( I use the front matter as if it was a struct ) which I do not intend to have a page for. Maybe that is a mistake, please let me know if there is a better way to store lists of data. 

Here is a suggestion on how the config.yml could be setup:
```
collections:
  output: true
  - my_collection1
  - my_collection2
  - my_collection3

autopages:
  enabled: true
  collections:
    #default collections config
    layouts: 
      - 'autopage_collection.html'
    title: 'Posts in collection :coll'
    permalink: '/collection/:coll'
    #specific config
    my_collection2:
        enabled: false
    my_collection3:
        layouts: 
           - 'my_collection3_custom_layout.html'
        permalink: '/custom_permalink/'
```

If I understand correclty I could have multiple layouts and I could generate all the pages and simply link the ones I will be using. But even though I do not have any links to some of these pages they could still be accessed by typing the url manually. That means it is not a big problem but generating pages that won't be used is still a waste of space.

Please let me know if I am mistaken and there is a way to diable the autopage for some collections
