### ISSUE TITLE
Providing custom extension results in wrong first_page_url

### ISSUE THREAD

**Issue by ashmaroli** [sverrirs/jekyll-paginate-v2#146]
With the following configuration:
```yaml
pagination:
  enabled:      true
  extension:    "json"
  sort_field:   "date"
  sort_reverse: true
```
Pagination results in:
```
_site/index.json.html
_site/page2/index.json
_site/page3/index.json
...
```

This has been reproduced on both `v2.0.0` and `v2.1.0`
