### ISSUE TITLE
Pagination for collection and dir_s_mkdir error

### ISSUE THREAD

**Issue by baszczewski** [sverrirs/jekyll-paginate-v2#150]
I am using this plugin in newest version: 2.1.0. Unfortunately after _jekyll serve_ I've got error:
```bash
jekyll 3.8.5 | Error:  File exists @ dir_s_mkdir - /media/data/projects/test/_site/freebies/index.html
```

Important part of my _config.yml:
```yml
plugins:
  - jekyll-paginate-v2

collections:
  freebies:
    output: true
    permalink: /freebies/:path/

pagination:
  enabled: true
  permalink: '/page/:num/'
  sort_reverse: true
  per_page: 3
  trail: 
    before: 2
    after: 2

autopages:
  enabled: true
  collections:
    enabled: true
    title: 'Posts in collection :coll' # :coll is replaced by the collection name
    permalink: '/:coll'

defaults:
  - scope:
      path: ""
      type: "freebies"
    values:
      layout: "freebies-post"
```

My freebies posts are located in "_freebies" directory (I've got 4 files here - only markdowns). I don't have in my project file described in error log like: "freebies/index.html".

What is weird here is that structure work's until option pagination->per_page is bigger than count of files inside my collection.

Do you have any idea what I can do here?
