### ISSUE TITLE
pagination.title doesn't seem to be doing its thing

### ISSUE THREAD

**Issue by pmpinto** [sverrirs/jekyll-paginate-v2#164]
Inside `_config.yml` I have:
```yml
title: "Hello"
pagination:
    enabled: true
    per_page: 1
    title: "NOP"
```

I was expecting:
`NOP`

I got:
`Page [X] of [Y] for NOP | Hello`

This might be related to the `jekyll-seo-tag` plugin since that's the one injecting the title.
Is there a way to work around this?

**Comment by haltepunkt** [comment]
I'm experiencing the same issue, too.

I would like to configure a completely localized title, such as _Seite 2 von 3_.

**Comment by haltepunkt** [comment]
Sorry, I totally overlooked `{% seo title=false %}`.

> **Disabling <title> output**
> If for some reason, you don't want the plugin to output <title> tags on each page, simply invoke the plugin within your template like so:
> `{% seo title=false %}`

Source: [https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/advanced-usage.md](https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/advanced-usage.md)

**Comment by pmpinto** [comment]
That's not exactly what I was looking for, but that's some additional info I didn't know about.

What I ended up doing (just now) was changing `pagination.title` to `""`. This way the output (considering the example config above) would be:
`Page [X] of [Y] for Hello | [site.description]`

That's something I can live with, but I would like `Page [X] of [Y] for` to be somewhat configurable.

**Comment by fagcinsk** [comment]
@haltepunkt so, how you used to make an alternative title? Are you checking for seo title and if not exists using alternative one?

**Comment by sverrirs** [comment]
Could you please upgrade to https://rubygems.org/gems/jekyll-paginate-v2/versions/3.0.0 and test again for me?

**Comment by vuojo** [comment]
Still broken.

```
# Pagination Settings
pagination:
  enabled: true
  per_page: 2
  permalink: '/sivu/:num/'
  limit: 0
  title: "KEKW"
  sort_field: 'date'
  sort_reverse: true

```

`<title>Page 2 of 3 for KEKW | Your awesome title</title>`
