### ISSUE TITLE
Autopages can't disable generating categories and collections pages

### ISSUE THREAD

**Issue by jubyshu** [sverrirs/jekyll-paginate-v2#172]
My config is as below: 
```yaml
pagination:
  enabled: true
  per_page: 9
  permalink: '/page/:num/'
  title: ':title'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

autopages:
  enabled: true
  tags:
    layouts: 
      - 'autopage_tags.html'
    title: 'Tag - :tag'
    permalink: '/tags/:tag'
```
But when I build the website on my PC, it still tries to generate categories and collections pages, and return errors that `reading file /_layouts/autopage_category.html: No such file or directory`. So how to disable it?

**Comment by evertonfraga** [comment]
I had this problem too. Do you mind sharing how you solved it?

**Comment by jubyshu** [comment]
> I had this problem too. Do you mind sharing how you solved it?

I use the codes as below and it works.

```
autopages:
  enabled: true
  categories: 
    enabled: false
  collections:
    enabled: false
  tags:
    enabled: true
    layouts: 
      - 'autopage_tags.html'
    title: 'Tag - :tag'
    permalink: '/tags/:tag'
```
