### ISSUE TITLE
Cannot use category's name (not title) in permalink with autopages

### ISSUE THREAD

**Issue by axeleroy** [sverrirs/jekyll-paginate-v2#193]
Hello,

I am migrating a website from Wordpress and in order to not create dead links I would like to use the category's filename in the permalink when using autopages, instead of the slugged title.

For example I have the following category in `_category/emplois.md`
```
---
title: "Offres d'emploi"
category: "Offres d'emploi"
---
```

With the following `_config.yaml`
```
collections:
  category:
    permalink: /category/:name/index.html
autopages:
  enabled: true
  categories:
    layouts:
      - "autopage_category.html"
    title: ":cat"
    permalink: "/category/:cat"
```

While I was expecting the categories to be in `category/emplois`, they end up in `category/offres+d'emploi` instead.

I could not find if there was any other tag like `:name` to put in the permalink, does this feature exist?

**Comment by axeleroy** [comment]
Nevermind, I came back to this issue and have found the solution:

```yaml
collections:
  pages:
    output: true
    permalink: "/:title"
  category:
    output: false
autopages:
  enabled: true
  categories:
    layouts:
      - "autopage_category.html"
    title: ":cat"
    slugify:
      mode: "ascii"
      case: true
    permalink: "/category/:cat/"
```
