### ISSUE TITLE
Multiple collection with different collection pages uses wrong template/layout

### ISSUE THREAD

**Issue by vunski** [sverrirs/jekyll-paginate-v2#202]
### Description

Jekyll ver. 4.1.1

/blog/index.html

```
---
layout: default
title: Blog
permalink: /blog
pagination:
  enabled: true
  collection: blog-posts
---
```

/anotherblog/index.html

```
---
layout: another-default
title: Another Blog
permalink: /anotherblog
pagination:
  enabled: true
  collection: another-blog-posts
---
```

Both sites show correct blog posts, but `/blog` uses the layout of `/anotherblog`, removing content from any of the two html files, then both sites use their own layout. The problem appears when including in the empty html file a liquid syntax. for e.g. `<p>{{ site.example.greeting }}</p>` and the page will show all the posts, even thought it should only show the paragraph.
