### ISSUE TITLE
Page link got 404

### ISSUE THREAD

**Issue by FavorMylikes** [sverrirs/jekyll-paginate-v2#221]
And I use `minimal-mistakes-jekyll` as theme
My `_config.ymkl`
```yml
pagination: # jekyll-paginate-v2
  enabled: true
  debug: true  # open debug
  per_page: 5
  permalink: '/blog/page/:num/'
  sort_field: 'date'
  sort_reverse: true
  trail:
    before: 2
    after: 2
```

debug output
```log
AutoPages: Disabled/Not configured in site.config.
Pagination: ----------------------------
Pagination: Page: index.html
Pagination:  Active configuration
Pagination:   Enabled:          true
Pagination:   Items per page:   5
Pagination:   Permalink:        /blog/page/:num/
Pagination:   Title:            :title - page :num
Pagination:   Limit:            0
Pagination:   Sort by:          date
Pagination:   Sort reverse:     true
Pagination:  Active Filters
Pagination:   Collection:       posts
Pagination:   Offset:           0
Pagination:   Category:         [Not set]
Pagination:   Tag:              [Not set]
Pagination:   Locale:           [Not set]
Pagination:  Filtering by: Category   11 => 11
Pagination:  Filtering by: Tag        11 => 11
Pagination:  Filtering by: Locale     11 => 11
Pagination: Rolling through the date fields for all documents
Pagination: Complete, processed 1 pagination page(s)
Jekyll Feed: Generating feed for posts
```

output
```html
<a href="/baseurl/page2">2</a>
```

seems `paginator` has some wrong var.

Is there somebody meet this before?

**Comment by fidelnamisi** [comment]
I'm having the same issue. I haven't found a solution yet.

**Comment by me-nkr** [comment]
Facing the same issue

**Comment by schmitzCatz** [comment]
Can confirm, something is wrong...

### Config
```yaml
pagination:
  enabled: true 
  debug: true
  per_page: 3  
  permalink: '/page/:num/'
  sort_field: 'date'
  sort_reverse: true
  trail: 
    before: 2
    after: 2
```
### Debug
```bash
Pagination: ----------------------------
Pagination: Page: _pages/index.html
Pagination:  Active configuration
Pagination:   Enabled:          true
Pagination:   Items per page:   3
Pagination:   Permalink:        /page/:num/
Pagination:   Title:            :title - page :num
Pagination:   Limit:            0
Pagination:   Sort by:          date
Pagination:   Sort reverse:     true
Pagination:  Active Filters
Pagination:   Collection:       posts
Pagination:   Offset:           0
Pagination:   Category:         [Not set]
Pagination:   Tag:              [Not set]
Pagination:   Locale:           [Not set]
Pagination:  Filtering by: Category    7 => 7
Pagination:  Filtering by: Tag         7 => 7
Pagination:  Filtering by: Locale      7 => 7
Pagination: Rolling through the date fields for all documents
Pagination: Complete, processed 1 pagination page(s)
            done in 5.477 seconds.
```
### Rendering
```liquid
{{ site.paginate_path | relative_url }}
```
`/page:num`
### Quickfix

```liquid
{{ site.paginate_path | relative_url | replace: ':num', '/:num' | replace: ':num', page}}
```

Cheers,

Oliver
