### ISSUE TITLE
Is posible to use display_name and other separators on the title options for autopages of tags?

### ISSUE THREAD

**Issue by Lewatoto** [sverrirs/jekyll-paginate-v2#225]
There exist some way to for example in the autopages config section use the original value of the tag/collection as option for the title? 
```yaml
autopages:
  enabled: true
  tags:
    layouts:
      - 'etiquetas.html'
    title: ":tag" # something like :tag_original to get Linux instead linux as page title?
    permalink: '/etiqueta/:tag/'
    silent: false
    slugify:
      mode: 'default' 
      case: false
```
I'm asking this because if not add the tag title for the autopages, the jekyll-seo plugin only takes the value of the title in pagination to make all the metadata that include the title.
