### ISSUE TITLE
Content overwriting though the permalinks are set

### ISSUE THREAD

**Issue by bastiweb** [sverrirs/jekyll-paginate-v2#229]
Hey,
I have the following problem:
The content of one page overwrites the content of another

See here:
https://staging.veilofsound.com/reviews/pagination.html
https://staging.veilofsound.com/interviews/pagination.html

Header reviews:
```yml
  permalink: /reviews
  pagination: 
    enabled: true
    tag: review
    permalink: 'page:num/reviews.html'
```

Header interviews:
```yml
permalink: /interviews/
  pagination: 
    enabled: true
    tag: interview
    permalink: 'page:num/interviews.html'
```

_config.yml:
```yml
pagination:
  enabled: true
  per_page: 25
  indexpage: 'pagination'
  sort_reverse: true
```

Did I do something wrong in my configuration?

I think I have followed the steps described under https://github.com/sverrirs/jekyll-paginate-v2/blob/master/README-GENERATOR.md#my-pagination-pages-are-overwriting-each-others-pages
