### ISSUE TITLE
Wrong pagination link

### ISSUE THREAD

**Issue by me-nkr** [sverrirs/jekyll-paginate-v2#235]
I have a category with an `index.html`, here's my directory structure
```
root/
  |- _config.yml
  |- cars/
    |- index.html
    |- _posts/
```
and the `index.html` front matter looks like this
```yaml
---
layout: single
title: name of car
pagination:
  enabled: true
  category: cars
  permalink: /:num/
---
```
when the site is built, I can see a directory named 2 with an `index.html` inside. Also I am able to find the next page at URL *`/cars/2/`**. But the link to page 2 is **`/page2`**
```html
<li><a href="/page2">Next</a></li>
```

Is this a bug or is it happening because of some configuration mistakes ?
