### ISSUE TITLE
What is the maximum number of jekyll Items per page

### ISSUE THREAD

**Issue by y377** [sverrirs/jekyll-paginate-v2#245]
hi @sverrirs !
What is the maximum number of jekyll Items per page?
I set the display of 15 per page, but both debug and the final page show 10. May I ask what should I do if I change it? thank you!
 ## my _config.yml:
```yml
pagination:
  trail: 
    before: 1 # The number of links before the current page
    after:  1 # The number of links after the current page 
   limit: 15
```
![image](https://user-images.githubusercontent.com/58632405/206700279-60542cf0-aaeb-4a04-942a-301d2a09fe56.png)
![image](https://user-images.githubusercontent.com/58632405/206701364-b70a7cdc-9a8f-4710-9c47-912ff5303477.png)
