### ISSUE TITLE
The first page's URL contains `index.html` despite the permalink opting out of it

### ISSUE THREAD

**Issue by CookiePLMonster** [sverrirs/jekyll-paginate-v2#263]
With the global configuration like this:
```
pagination:
  enabled: true
  per_page: 5
  title: ":title"
  sort_reverse: true
```

and the page configured to paginate a collection through its front matter:
```
permalink: /updates/
pagination:
  enabled: true
  per_page: 10
  collection: updates
```

I then build the navigation bar by iterating through `site.pages`, and I found that the `page.url` of the Updates website became `/updates/index.html`, even though the permalink should indicate otherwise:

![Image](https://github.com/user-attachments/assets/50427d94-d4b5-45ae-98ee-646ffcc2a617)

Curiously, on pagination itself, `paginator.first_page_path` respects the permalink and the URL is `/updates/`, so this issue is isolated to `site.pages`.
