### ISSUE TITLE
Pagination: Is enabled, but I couldn't find any pagination page.

### ISSUE THREAD

**Issue by alvarotrigo** [sverrirs/jekyll-paginate-v2#48]
Using jekyll 3.6.2 I followed the instructions and I still got the following message when doing `bundle exec jekyll serve`:

> Pagination: Is enabled, but I couldn't find any pagination page. Skipping pagination. Pages must have 'pagination: enabled: true' in their front-matter for pagination to work.

My _config.yml file contains the following:

```
# Pagination Settings
pagination:
  enabled: true
  per_page: 3
  permalink: '/page/:num/'
  title: ':title - page :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
```

And the layout `home` where I want the pagination for my posts looks like this:

```html
---
layout: default
pagination:
  enabled: true
---

<div class="home">

    <h1 class="page-heading">Posts</h1> {{ content }}

    <ul class="post-list">
        {% for post in paginator.posts %}
        <li class="post-item">
            <span class="post-meta">{{ post.date | date: "%b %-d, %Y" }}</span>
            <div class="post-image">
                <img class="post-image" src="{{ post.image }} " />
            </div>
            <h2 class="post-item-title">
          <a class="post-link" href="{{ post.url | relative_url }}">{{ post.title | escape }}</a>
        </h2>
            <div class="post-abstract">{{ post.excerpt | strip_html | truncatewords:20 }}</div>
        </li>{% endfor %}
    </ul>
</div>
```

What am I doing wrong? Why `paginator.posts` seems to be empty? 
It is not showing any post.

My Gemfile contains:

```
# If you have any plugins, put them here!
group :jekyll_plugins do
   gem "jekyll-feed", "~> 0.6"
   gem "jekyll-paginate-v2"
end
```
