### ISSUE TITLE
Autopages requires explicit opt-out when only using one section (just want categories)

### ISSUE THREAD

**Issue by maxgardner** [sverrirs/jekyll-paginate-v2#83]
Hello! This project is great. Thank you for working on it and maintaining it!

I did run across a potential issue while using Autopages. The documentation says to omit any sections you don't want to enable auto-generation for, but it seems that if you enable it for one, you must explicitly disable it for the other available sections. Apologies if this is intended behavior and I've misread the documentation.

### My initial attempt
_config.yml:
```
autopages:
    enabled: true
    categories:
      layouts:
        - default.html
      title: :cat Events
      permalink: /category/:cat
```
Console:
```
AutoPages: Generating tags pages
AutoPages: Generating categories pages
AutoPages: Generating collections pages

Error reading file /~project-path~/_layouts/autopage_collection.html: No such file or directory @ rb_sysopen - /~project-path~/autopage_collection.html

Build Warning: Layout 'autopage_collection' requested in .html does not exist.
```

It tried to generate pages for both tags and collections, despite me not specifying those in the config file. For some reason, it generated the tag pages fine - I think probably because I'm not using that feature in Jekyll currently, so there wasn't really anything to create.

### The Fix
I'm able to resolve this by explicitly disabling the sections I don't want:

_config.yml
```
autopages:
    enabled: true
    categories:
      layouts:
        - default.html
      title: :cat Events
      permalink: /category/:cat
    collections:
      enabled: false
    tags:
      enabled: false
```
Console:
```
AutoPages: tags pages are disabled/not configured in site.config.
AutoPages: Generating categories pages
AutoPages: collections pages are disabled/not configured in site.config.
```

It would be great if Autopages could generate pages for only the sections included in config file.

**Comment by sverrirs** [comment]
Hi Max, thanks for the kind words and the detailed report. 

Indeed you´ve stumbled onto a rather annoying behavior in the code. I think a solution would be to imply false for the enabled if no layouts are found. I will give this a thought and come up with a solution that doesn't require explicitly disabling features. Might be a few days though :)

**Comment by BlkPingu** [comment]
thanks for posting this. I stumbled across this too and just fixed it due to this documentation @maxgardner

**Comment by jackwish** [comment]
Hi guys, this seems to be broken. Need to setup `enabled: false` now. I can workaround it but it would be great to fix it. And, thanks for the awesome tool!

I am testing my config, only to generate tags, and here is the YAML
```yaml
autopages:
  enabled: true

  tags:
    layouts:
      - 'list.html'
    title: ':tag'
    permalink: '/tag/:tag'
    silent: false
    slugify:
      mode: 'default'   # :tag is slugified.
      case: false
```

And Jekyll reports that cannot find the layout and has conflicts (I am preparing the category page manually)
```
         AutoPages: Generating tags pages
         AutoPages: Generating categories pages     <------- see this
Error reading file /Users/wzh/workspace/migrating-blog/blog.git/_layouts/autopage_category.html: No such file or directory @ rb_sysopen - /Users/wzh/workspace/migrating-blog/blog.git/_layouts/autopage_category.html
Error reading file /Users/wzh/workspace/migrating-blog/blog.git/_layouts/autopage_category.html: No such file or directory @ rb_sysopen - /Users/wzh/workspace/migrating-blog/blog.git/_layouts/autopage_category.html
         AutoPages: Generating collections pages
Error reading file /Users/wzh/workspace/migrating-blog/blog.git/_layouts/autopage_collection.html: No such file or directory @ rb_sysopen - /Users/wzh/workspace/migrating-blog/blog.git/_layouts/autopage_collection.html
        Pagination: Complete, processed 12 pagination page(s)
```
