### ISSUE TITLE
Multiple passes on autopages?

### ISSUE THREAD

**Issue by djoos** [sverrirs/jekyll-paginate-v2#91]
Hi there,

first of all: great work on this paginate plugin - really loving it!

I'm currently looking into using the [autopages](https://github.com/sverrirs/jekyll-paginate-v2/blob/master/README-AUTOPAGES.md#simple-configuration) functionality to generate tag and category pages. The issue is that I've got posts in different languages (ie. locale: en/locale: nl on each post's YAML front matter) and I feel I would need to be able to do "multiple passes" on the autopages, each with slightly different settings, ie.
```yaml
autopages:
  enabled: true

  tags:
    - english
      layouts:
        - 'autopage_tag_en.html' # with pagination locale set to en in front matter
      title: 'The tag: :tag'
      permalink: '/en/here-are-the-tags/:tag'
    - nederlands
      layouts:
        - 'autopage_tag_nl.html' # with pagination locale set to nl in front matter
      title: 'De tag: :tag'
      permalink: '/nl/hier-zijn-de-tags/:tag'
    - ...
```
...allowing the autopages functionality to generate /en/here-are-the-tags/* pages and /nl/hier-zijn-de-tags/* pages.

It's obviously not possible to have multiple 'tags' keys underneath autopages, so having a "tags" array array could potentially work. Would something like "multiple passes" be the way to get to the desired result, or am I just making things more complicated than they should and am I overlooking something that allows i18n/l10n tags/categories?

Thanks in advance for your feedback!
David
