### ISSUE TITLE
Front matter defaults get "lost"

### ISSUE THREAD

**Issue by djoos** [sverrirs/jekyll-paginate-v2#92]
Hi there,

it seems that the pages generated via the paginate v2 plugin "loose" the [front matter defaults](https://jekyllrb.com/docs/configuration/#front-matter-defaults).

# Replicating the issue

In an existing project that makes use of the jekyll-paginate-v2 plugin:

Add some [front matter defaults](https://jekyllrb.com/docs/configuration/#front-matter-defaults) in config.yml
```
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      some_setting:
        key: "a default value"
  -
    scope:
      path: "projects" # all files in the projects-folder
    values:
      some_setting:
        key: "another value"
```

Output the key's value in _layouts/default.html
```
Key value is "{{ page.some_setting.key }}"
```

Create a "test-no-pagination.md" file in a new "projects" folder in the root of the Jekyll project, with the following front matter:
```
---
layout: default
---
```

Create a "test-pagination.md" in the "projects" folder as well, with the following front matter:
```
---
layout: default
pagination:
  enabled: true
  category: projects
  permalink: /:num/
---
```

When generating the Jekyll site, you can spot _Key value is "another value"_ in _site/projects/test-no-pagination.html while _Key value is "a default value"_ in _site/projects/index.html... The expected behaviour was to get _Key value is "another value"_ in both files, as per the front matter defaults setup in _config.yml.

I'll make some time to debug the issue deeper, but wanted to flag this here first as any thoughts on/references to the plugin code to focus on in particular are welcome...

Thanks in advance!
David
